/**
 * @file Auto-generated TypeScript bindings for FinchippayContract.
 *
 * Generated by `stellar contract bindings typescript`.
 * DO NOT EDIT MANUALLY — regenerate via `scripts/gen-contract-bindings.sh`.
 *
 * @see contracts/finchippay-contract/src/lib.rs
 */

import {
  Contract,
  Horizon,
  nativeToScVal,
  Networks,
  rpc,
  scValToNative,
  TransactionBuilder,
  Account,
  Transaction,
  xdr,
} from "@stellar/stellar-sdk";

// ─── Config helpers (mirrors lib/stellarConfig.ts) ──────────────────────────

function getNetworkConfig(): { network: string; horizonUrl: string } {
  if (typeof window === "undefined") {
    const network = (process.env.NEXT_PUBLIC_STELLAR_NETWORK || "testnet") as
      | "testnet"
      | "mainnet";
    return network === "mainnet"
      ? { network: "mainnet", horizonUrl: "https://horizon.stellar.org" }
      : { network: "testnet", horizonUrl: "https://horizon-testnet.stellar.org" };
  }
  const stored = localStorage.getItem("finchippay:network");
  if (stored) {
    try {
      return JSON.parse(stored);
    } catch {
      // ignore
    }
  }
  return { network: "testnet", horizonUrl: "https://horizon-testnet.stellar.org" };
}

function getNetworkPassphrase(): string {
  const cfg = getNetworkConfig();
  return cfg.network === "mainnet" ? Networks.PUBLIC : Networks.TESTNET;
}

function getSorobanRpcUrl(): string {
  const cfg = getNetworkConfig();
  if (cfg.network === "mainnet") return "https://soroban.stellar.org";
  return "https://soroban-testnet.stellar.org";
}

let _server: Horizon.Server | null = null;
function getServer(): Horizon.Server {
  const cfg = getNetworkConfig();
  if (!_server || _server.serverURL.toString() !== cfg.horizonUrl) {
    _server = new Horizon.Server(cfg.horizonUrl);
  }
  return _server;
}

let _sorobanServer: rpc.Server | null = null;
function getSorobanServer(): rpc.Server {
  const url = getSorobanRpcUrl();
  if (!_sorobanServer || _sorobanServer.serverURL.toString() !== url) {
    _sorobanServer = new rpc.Server(url);
  }
  return _sorobanServer;
}

const BASE_FEE_STROOPS = 100;
const TX_TIMEOUT_SECONDS = 60;

// ─── Enums ─────────────────────────────────────────────────────────────────

export enum EscrowStatus {
  Pending = "Pending",
  Released = "Released",
  Cancelled = "Cancelled",
}

export enum MultiSigStatus {
  Pending = "Pending",
  Executed = "Executed",
  Cancelled = "Cancelled",
}

// ─── Struct types ──────────────────────────────────────────────────────────

export interface TipRecord {
  from: string;
  to: string;
  amount: string;
  ledger: number;
  memo: string;
}

export interface ReceiptMetadata {
  from: string;
  to: string;
  amount: string;
  timestamp: number;
  memo: string;
  ledger: number;
}

export interface Escrow {
  id: number;
  from: string;
  to: string;
  token: string;
  amount: string;
  releaseLedger: number;
  status: EscrowStatus;
  memo: string;
}

export interface Stream {
  id: number;
  payer: string;
  recipient: string;
  token: string;
  ratePerLedger: string;
  deposited: string;
  claimed: string;
  startLedger: number;
  closed: boolean;
}

export interface MultiSigProposal {
  id: number;
  proposer: string;
  recipient: string;
  token: string;
  amount: string;
  threshold: number;
  signers: string[];
  approvals: string[];
  status: MultiSigStatus;
  expirationLedger: number;
}

// ─── ScVal helpers ─────────────────────────────────────────────────────────

function scvAddress(v: string) {
  return nativeToScVal(v, { type: "address" });
}

function scvI128(v: bigint | number | string) {
  return nativeToScVal(BigInt(v), { type: "i128" });
}

function scvU32(v: number) {
  return nativeToScVal(v, { type: "u32" });
}

function scvSymbol(v: string) {
  return nativeToScVal(v, { type: "symbol" });
}

function scvVec(vals: xdr.ScVal[]) {
  return xdr.ScVal.scvVec(vals);
}

function scvAddressVec(addrs: string[]) {
  return scvVec(addrs.map(scvAddress));
}

function scvI128Vec(vals: (bigint | number | string)[]) {
  return scvVec(vals.map(scvI128));
}

function scvSymbolVec(vals: string[]) {
  return scvVec(vals.map(scvSymbol));
}

// ─── Decoders ──────────────────────────────────────────────────────────────

function decodeMap(retval: xdr.ScVal): Record<string, unknown> {
  return scValToNative(retval) as Record<string, unknown>;
}

function decodeU32(retval: xdr.ScVal): number {
  return Number(scValToNative(retval));
}

function decodeI128(retval: xdr.ScVal): string {
  return String(scValToNative(retval));
}

function decodeTuple3(retval: xdr.ScVal): [number, number, number] {
  const v = scValToNative(retval);
  return [Number(v[0]), Number(v[1]), Number(v[2])];
}

function addr(m: Record<string, unknown>, key: string): string {
  return String(m[key]);
}

function big(m: Record<string, unknown>, key: string): string {
  return String(m[key]);
}

function u32(m: Record<string, unknown>, key: string): number {
  return Number(m[key]);
}

function bool(m: Record<string, unknown>, key: string): boolean {
  return Boolean(m[key]);
}

function decodeEscrowStatus(s: unknown): EscrowStatus {
  if (s === "Released" || s === 1) return EscrowStatus.Released;
  if (s === "Cancelled" || s === 2) return EscrowStatus.Cancelled;
  return EscrowStatus.Pending;
}

function decodeMultiSigStatus(s: unknown): MultiSigStatus {
  if (s === "Executed" || s === 1) return MultiSigStatus.Executed;
  if (s === "Cancelled" || s === 2) return MultiSigStatus.Cancelled;
  return MultiSigStatus.Pending;
}

function decodeScValVec(retval: xdr.ScVal): unknown[] {
  const v = scValToNative(retval);
  return Array.isArray(v) ? v : [];
}

function decodeStream(m: Record<string, unknown>): Stream {
  return {
    id: u32(m, "id"),
    payer: addr(m, "payer"),
    recipient: addr(m, "recipient"),
    token: addr(m, "token"),
    ratePerLedger: big(m, "rate_per_ledger"),
    deposited: big(m, "deposited"),
    claimed: big(m, "claimed"),
    startLedger: u32(m, "start_ledger"),
    closed: bool(m, "closed"),
  };
}

function decodeEscrow(m: Record<string, unknown>): Escrow {
  return {
    id: u32(m, "id"),
    from: addr(m, "from"),
    to: addr(m, "to"),
    token: addr(m, "token"),
    amount: big(m, "amount"),
    releaseLedger: u32(m, "release_ledger"),
    status: decodeEscrowStatus(m["status"]),
    memo: String(m["memo"] ?? ""),
  };
}

function decodeMultiSig(m: Record<string, unknown>): MultiSigProposal {
  const signersRaw = m["signers"];
  const approvalsRaw = m["approvals"];
  return {
    id: u32(m, "id"),
    proposer: addr(m, "proposer"),
    recipient: addr(m, "recipient"),
    token: addr(m, "token"),
    amount: big(m, "amount"),
    threshold: u32(m, "threshold"),
    signers: Array.isArray(signersRaw) ? signersRaw.map(String) : [],
    approvals: Array.isArray(approvalsRaw) ? approvalsRaw.map(String) : [],
    status: decodeMultiSigStatus(m["status"]),
    expirationLedger: u32(m, "expiration_ledger"),
  };
}

// ─── Simulate a read-only contract call ────────────────────────────────────

async function simulateView(
  contractId: string,
  method: string,
  args: xdr.ScVal[],
  source = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF",
): Promise<rpc.Api.SimulateTransactionSuccessResponse | null> {
  const contract = new Contract(contractId);
  const tx = new TransactionBuilder(new Account(source, "0"), {
    fee: String(BASE_FEE_STROOPS),
    networkPassphrase: getNetworkPassphrase(),
  })
    .addOperation(contract.call(method, ...args))
    .setTimeout(30)
    .build();

  const sim = await getSorobanServer().simulateTransaction(tx);
  if (rpc.Api.isSimulationSuccess(sim) && sim.result) {
    return sim;
  }
  return null;
}

// ─── Simulate a write (build + preflight) ──────────────────────────────────

async function buildAndPrepare(
  contractId: string,
  sourcePublicKey: string,
  method: string,
  args: xdr.ScVal[],
  timeout = TX_TIMEOUT_SECONDS,
): Promise<Transaction> {
  const sourceAccount = await getServer().loadAccount(sourcePublicKey);
  const contract = new Contract(contractId);

  const tx = new TransactionBuilder(sourceAccount, {
    fee: String(BASE_FEE_STROOPS),
    networkPassphrase: getNetworkPassphrase(),
  })
    .addOperation(contract.call(method, ...args))
    .setTimeout(timeout)
    .build();

  const simulated = await getSorobanServer().simulateTransaction(tx);
  if (rpc.Api.isSimulationError(simulated)) {
    throw new Error(`Simulation failed for ${method}: ${simulated.error}`);
  }

  return getSorobanServer().prepareTransaction(tx);
}

// ─── Contract Client ───────────────────────────────────────────────────────

export class FinchippayContractClient {
  private contractId: string;

  constructor(contractId: string) {
    this.contractId = contractId;
  }

  getContractId(): string {
    return this.contractId;
  }

  // ── Admin ──────────────────────────────────────────────────────────────

  async initialize(source: string, admin: string): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "initialize", [
      scvAddress(admin),
    ]);
  }

  async transferAdmin(
    source: string,
    currentAdmin: string,
    newAdmin: string,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "transfer_admin", [
      scvAddress(currentAdmin),
      scvAddress(newAdmin),
    ]);
  }

  async getAdmin(
    source = "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF",
  ): Promise<string> {
    const sim = await simulateView(this.contractId, "get_admin", [], source);
    if (!sim) throw new Error("get_admin simulation failed");
    return String(scValToNative(sim.result!.retval));
  }

  async isPaused(source?: string): Promise<boolean> {
    const sim = await simulateView(this.contractId, "is_paused", [], source);
    if (!sim) return false;
    return Boolean(scValToNative(sim.result!.retval));
  }

  async pause(source: string, caller: string): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "pause", [
      scvAddress(caller),
    ]);
  }

  async unpause(source: string, caller: string): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "unpause", [
      scvAddress(caller),
    ]);
  }

  async setPauser(
    source: string,
    admin: string,
    pauser: string,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "set_pauser", [
      scvAddress(admin),
      scvAddress(pauser),
    ]);
  }

  async getPauser(source?: string): Promise<string | null> {
    const sim = await simulateView(
      this.contractId,
      "get_pauser",
      [],
      source,
    );
    if (!sim || !sim.result) return null;
    const val = scValToNative(sim.result.retval);
    return val ? String(val) : null;
  }

  async getVersion(source?: string): Promise<number> {
    const sim = await simulateView(
      this.contractId,
      "get_version",
      [],
      source,
    );
    if (!sim) return 0;
    return decodeU32(sim.result!.retval);
  }

  async upgrade(
    source: string,
    admin: string,
    newWasmHash: string,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "upgrade", [
      scvAddress(admin),
      nativeToScVal(newWasmHash, { type: "bytes" }),
    ]);
  }

  // ── Tips ────────────────────────────────────────────────────────────────

  async sendTip(
    source: string,
    tokenAddress: string,
    from: string,
    to: string,
    amount: bigint,
    memo: string,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "send_tip", [
      scvAddress(tokenAddress),
      scvAddress(from),
      scvAddress(to),
      scvI128(amount),
      scvSymbol(memo),
    ]);
  }

  async getTipTotal(
    recipient: string,
    source?: string,
  ): Promise<string> {
    const sim = await simulateView(
      this.contractId,
      "get_tip_total",
      [scvAddress(recipient)],
      source,
    );
    if (!sim) return "0";
    return decodeI128(sim.result!.retval);
  }

  async getTipCount(
    recipient: string,
    source?: string,
  ): Promise<number> {
    const sim = await simulateView(
      this.contractId,
      "get_tip_count",
      [scvAddress(recipient)],
      source,
    );
    if (!sim) return 0;
    return decodeU32(sim.result!.retval);
  }

  async getTipRecord(
    recipient: string,
    index: number,
    source?: string,
  ): Promise<TipRecord | null> {
    const sim = await simulateView(
      this.contractId,
      "get_tip_record",
      [scvAddress(recipient), scvU32(index)],
      source,
    );
    if (!sim) return null;
    const m = decodeMap(sim.result!.retval);
    return {
      from: addr(m, "from"),
      to: addr(m, "to"),
      amount: big(m, "amount"),
      ledger: u32(m, "ledger"),
      memo: String(m["memo"] ?? ""),
    };
  }

  // ── Receipts ────────────────────────────────────────────────────────────

  async mintReceipt(
    source: string,
    from: string,
    to: string,
    amount: bigint,
    memo: string,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "mint_receipt", [
      scvAddress(from),
      scvAddress(to),
      scvI128(amount),
      scvSymbol(memo),
    ]);
  }

  async getReceiptCount(
    payer: string,
    source?: string,
  ): Promise<number> {
    const sim = await simulateView(
      this.contractId,
      "get_receipt_count",
      [scvAddress(payer)],
      source,
    );
    if (!sim) return 0;
    return decodeU32(sim.result!.retval);
  }

  async getReceipt(
    payer: string,
    index: number,
    source?: string,
  ): Promise<ReceiptMetadata | null> {
    const sim = await simulateView(
      this.contractId,
      "get_receipt",
      [scvAddress(payer), scvU32(index)],
      source,
    );
    if (!sim) return null;
    const m = decodeMap(sim.result!.retval);
    return {
      from: addr(m, "from"),
      to: addr(m, "to"),
      amount: big(m, "amount"),
      timestamp: Number(m["timestamp"] ?? 0),
      memo: String(m["memo"] ?? ""),
      ledger: u32(m, "ledger"),
    };
  }

  // ── Escrow ──────────────────────────────────────────────────────────────

  async createEscrow(
    source: string,
    tokenAddress: string,
    from: string,
    to: string,
    amount: bigint,
    releaseLedger: number,
    memo: string,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "create_escrow", [
      scvAddress(tokenAddress),
      scvAddress(from),
      scvAddress(to),
      scvI128(amount),
      scvU32(releaseLedger),
      scvSymbol(memo),
    ]);
  }

  async claimEscrowPartial(
    source: string,
    id: number,
    claimAmount: bigint,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "claim_escrow_partial", [
      scvU32(id),
      scvI128(claimAmount),
    ]);
  }

  async claimEscrow(
    source: string,
    id: number,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "claim_escrow", [
      scvU32(id),
    ]);
  }

  async cancelEscrow(
    source: string,
    id: number,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "cancel_escrow", [
      scvU32(id),
    ]);
  }

  async getEscrow(id: number, source?: string): Promise<Escrow | null> {
    const sim = await simulateView(
      this.contractId,
      "get_escrow",
      [scvU32(id)],
      source,
    );
    if (!sim) return null;
    return decodeEscrow(decodeMap(sim.result!.retval));
  }

  async getEscrowCount(source?: string): Promise<number> {
    const sim = await simulateView(
      this.contractId,
      "get_escrow_count",
      [],
      source,
    );
    if (!sim) return 0;
    return decodeU32(sim.result!.retval);
  }

  async getUserEscrows(
    recipient: string,
    source?: string,
  ): Promise<number[]> {
    const sim = await simulateView(
      this.contractId,
      "get_user_escrows",
      [scvAddress(recipient)],
      source,
    );
    if (!sim) return [];
    const val = decodeScValVec(sim.result!.retval);
    return val.map(Number);
  }

  // ── Streaming ──────────────────────────────────────────────────────────

  async openStream(
    source: string,
    tokenAddress: string,
    payer: string,
    recipient: string,
    ratePerLedger: bigint,
    deposit: bigint,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "open_stream", [
      scvAddress(tokenAddress),
      scvAddress(payer),
      scvAddress(recipient),
      scvI128(ratePerLedger),
      scvI128(deposit),
    ]);
  }

  async claimStream(
    source: string,
    streamId: number,
    recipient: string,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "claim_stream", [
      scvU32(streamId),
      scvAddress(recipient),
    ]);
  }

  async topUpStream(
    source: string,
    streamId: number,
    payer: string,
    amount: bigint,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "top_up_stream", [
      scvU32(streamId),
      scvAddress(payer),
      scvI128(amount),
    ]);
  }

  async closeStream(
    source: string,
    streamId: number,
    payer: string,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "close_stream", [
      scvU32(streamId),
      scvAddress(payer),
    ]);
  }

  async rejectStream(
    source: string,
    streamId: number,
    recipient: string,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "reject_stream", [
      scvU32(streamId),
      scvAddress(recipient),
    ]);
  }

  async transferStream(
    source: string,
    streamId: number,
    currentRecipient: string,
    newRecipient: string,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "transfer_stream", [
      scvU32(streamId),
      scvAddress(currentRecipient),
      scvAddress(newRecipient),
    ]);
  }

  async getStream(
    streamId: number,
    source?: string,
  ): Promise<Stream | null> {
    const sim = await simulateView(
      this.contractId,
      "get_stream",
      [scvU32(streamId)],
      source,
    );
    if (!sim) return null;
    return decodeStream(decodeMap(sim.result!.retval));
  }

  async getClaimable(
    streamId: number,
    source?: string,
  ): Promise<string> {
    const sim = await simulateView(
      this.contractId,
      "get_claimable",
      [scvU32(streamId)],
      source,
    );
    if (!sim) return "0";
    return decodeI128(sim.result!.retval);
  }

  async getStreamCount(source?: string): Promise<number> {
    const sim = await simulateView(
      this.contractId,
      "get_stream_count",
      [],
      source,
    );
    if (!sim) return 0;
    return decodeU32(sim.result!.retval);
  }

  // ── Multi-sig ───────────────────────────────────────────────────────────

  async createMultisig(
    source: string,
    tokenAddress: string,
    proposer: string,
    recipient: string,
    amount: bigint,
    threshold: number,
    signers: string[],
    expirationLedger: number,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "create_multisig", [
      scvAddress(tokenAddress),
      scvAddress(proposer),
      scvAddress(recipient),
      scvI128(amount),
      scvU32(threshold),
      scvAddressVec(signers),
      scvU32(expirationLedger),
    ]);
  }

  async approveMultisig(
    source: string,
    proposalId: number,
    signer: string,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "approve_multisig", [
      scvU32(proposalId),
      scvAddress(signer),
    ]);
  }

  async timeoutMultisig(
    source: string,
    proposalId: number,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "timeout_multisig", [
      scvU32(proposalId),
    ]);
  }

  async cancelMultisig(
    source: string,
    proposalId: number,
    proposer: string,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "cancel_multisig", [
      scvU32(proposalId),
      scvAddress(proposer),
    ]);
  }

  async getMultisig(
    proposalId: number,
    source?: string,
  ): Promise<MultiSigProposal | null> {
    const sim = await simulateView(
      this.contractId,
      "get_multisig",
      [scvU32(proposalId)],
      source,
    );
    if (!sim) return null;
    return decodeMultiSig(decodeMap(sim.result!.retval));
  }

  async getMultisigCount(source?: string): Promise<number> {
    const sim = await simulateView(
      this.contractId,
      "get_multisig_count",
      [],
      source,
    );
    if (!sim) return 0;
    return decodeU32(sim.result!.retval);
  }

  // ── Diagnostics ─────────────────────────────────────────────────────────

  async getContractStats(
    source?: string,
  ): Promise<[number, number, number]> {
    const sim = await simulateView(
      this.contractId,
      "get_contract_stats",
      [],
      source,
    );
    if (!sim) return [0, 0, 0];
    return decodeTuple3(sim.result!.retval);
  }

  // ── Batch send ──────────────────────────────────────────────────────────

  async batchSend(
    source: string,
    tokenAddress: string,
    from: string,
    recipients: string[],
    amounts: (bigint | number | string)[],
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "batch_send", [
      scvAddress(tokenAddress),
      scvAddress(from),
      scvAddressVec(recipients),
      scvI128Vec(amounts),
    ]);
  }

  async batchSendMulti(
    source: string,
    from: string,
    tokens: string[],
    recipients: string[],
    amounts: (bigint | number | string)[],
    memos: string[],
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "batch_send_multi", [
      scvAddress(from),
      scvAddressVec(tokens),
      scvAddressVec(recipients),
      scvI128Vec(amounts),
      scvSymbolVec(memos),
    ]);
  }

  // ── Swap / DEX ─────────────────────────────────────────────────────────

  async swapExactTokensForTokens(
    source: string,
    caller: string,
    tokenIn: string,
    tokenOut: string,
    amountIn: bigint | number | string,
    minAmountOut: bigint | number | string,
    path: string[],
  ): Promise<Transaction> {
    return buildAndPrepare(
      this.contractId,
      source,
      "swap_exact_tokens_for_tokens",
      [
        scvAddress(caller),
        scvAddress(tokenIn),
        scvAddress(tokenOut),
        scvI128(amountIn),
        scvI128(minAmountOut),
        scvAddressVec(path),
      ],
    );
  }

  async swapTokensForExactTokens(
    source: string,
    caller: string,
    tokenIn: string,
    tokenOut: string,
    amountOut: bigint | number | string,
    maxAmountIn: bigint | number | string,
    path: string[],
  ): Promise<Transaction> {
    return buildAndPrepare(
      this.contractId,
      source,
      "swap_tokens_for_exact_tokens",
      [
        scvAddress(caller),
        scvAddress(tokenIn),
        scvAddress(tokenOut),
        scvI128(amountOut),
        scvI128(maxAmountIn),
        scvAddressVec(path),
      ],
    );
  }

  async setFeeCollector(
    source: string,
    admin: string,
    collector: string,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "set_fee_collector", [
      scvAddress(admin),
      scvAddress(collector),
    ]);
  }

  async getFeeCollector(source?: string): Promise<string | null> {
    const sim = await simulateView(
      this.contractId,
      "get_fee_collector",
      [],
      source,
    );
    if (!sim) return null;
    return String(scValToNative(sim.result!.retval));
  }

  async setSwapFee(
    source: string,
    admin: string,
    newFeeBps: number,
  ): Promise<Transaction> {
    return buildAndPrepare(this.contractId, source, "set_swap_fee", [
      scvAddress(admin),
      scvU32(newFeeBps),
    ]);
  }

  async getSwapFee(source?: string): Promise<number> {
    const sim = await simulateView(this.contractId, "get_swap_fee", [], source);
    if (!sim) return 0;
    return decodeU32(sim.result!.retval);
  }
}
